---
name: Lint

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  superlinter:
    runs-on: ubuntu-latest

    # Skip on dependabot PRs
    if: startsWith(github.head_ref, 'dependabot') == false

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          DEFAULT_BRANCH: main
          RAILS_KEY_MASTER: ${{ secrets.RAILS_KEY_MASTER  }}
          LINTER_RULES_PATH: /
          RUBY_CONFIG_FILE: .rubocop.yml
          YAML_CONFIG_FILE: .yamllint.yml
          VALIDATE_ALL_CODEBASE: false